# Server Configuration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security?createDatabaseIfNotExist=true
    username: postgres
    password: 12
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog-master.xml
